// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-magic-comment"
export const version = "0.0.2"
export const displayName = "VSCode Magic Comment"
export const description = "Add annotations to magic comments"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "magic-comment.getLanguageConfig"

/**
 * Commands map registed by `ntnyq.vscode-magic-comment`
 */
export const commands = {
  /**
   * getLanguageConfig
   * @value `magic-comment.getLanguageConfig`
   */
  getLanguageConfig: "magic-comment.getLanguageConfig",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = 
  | "magic-comment.annotation"
  | "magic-comment.disabledCategories"
  | "magic-comment.disabledNames"
  | "magic-comment.enable"
  | "magic-comment.excludeFiles"
  | "magic-comment.includeFiles"
  | "magic-comment.supportLanguages"
  | "magic-comment.userComments"

export interface ConfigKeyTypeMap {
  "magic-comment.annotation": { 'after': { 'contentText': string; 'margin': string }; 'color': string },
  "magic-comment.disabledCategories": string[],
  "magic-comment.disabledNames": string[],
  "magic-comment.enable": boolean,
  "magic-comment.excludeFiles": string[],
  "magic-comment.includeFiles": string[],
  "magic-comment.supportLanguages": string[],
  "magic-comment.userComments": { 'category': string; 'description': string; 'examples': string[]; 'name': string; 'patterns': unknown; 'url': string }[],
}

export interface ConfigShorthandMap {
  annotation: "magic-comment.annotation",
  disabledCategories: "magic-comment.disabledCategories",
  disabledNames: "magic-comment.disabledNames",
  enable: "magic-comment.enable",
  excludeFiles: "magic-comment.excludeFiles",
  includeFiles: "magic-comment.includeFiles",
  supportLanguages: "magic-comment.supportLanguages",
  userComments: "magic-comment.userComments",
}

export interface ConfigShorthandTypeMap {
  annotation: { 'after': { 'contentText': string; 'margin': string }; 'color': string },
  disabledCategories: string[],
  disabledNames: string[],
  enable: boolean,
  excludeFiles: string[],
  includeFiles: string[],
  supportLanguages: string[],
  userComments: { 'category': string; 'description': string; 'examples': string[]; 'name': string; 'patterns': unknown; 'url': string }[],
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-magic-comment`
 */
export const configs = {
  /**
   * Magic comment annotation
   * @key `magic-comment.annotation`
   * @default `{ "after": { "contentText": "🚀", "margin": "0 0 0 0.5em" }, "color": "rgb(255, 189, 42)" }`
   * @type `object`
   */
  annotation: {
    key: "magic-comment.annotation",
    default: { "after": { "contentText": "🚀", "margin": "0 0 0 0.5em" }, "color": "rgb(255, 189, 42)" },
  } as ConfigItem<"magic-comment.annotation">,
  /**
   * Disabled by comments category
   * @key `magic-comment.disabledCategories`
   * @default `[]`
   * @type `array`
   */
  disabledCategories: {
    key: "magic-comment.disabledCategories",
    default: [],
  } as ConfigItem<"magic-comment.disabledCategories">,
  /**
   * Disabled by comments name
   * @key `magic-comment.disabledNames`
   * @default `[]`
   * @type `array`
   */
  disabledNames: {
    key: "magic-comment.disabledNames",
    default: [],
  } as ConfigItem<"magic-comment.disabledNames">,
  /**
   * Enable extension
   * @key `magic-comment.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "magic-comment.enable",
    default: true,
  } as ConfigItem<"magic-comment.enable">,
  /**
   * Exclude files
   * @key `magic-comment.excludeFiles`
   * @default `[]`
   * @type `array`
   */
  excludeFiles: {
    key: "magic-comment.excludeFiles",
    default: [],
  } as ConfigItem<"magic-comment.excludeFiles">,
  /**
   * Include files
   * @key `magic-comment.includeFiles`
   * @default `[]`
   * @type `array`
   */
  includeFiles: {
    key: "magic-comment.includeFiles",
    default: [],
  } as ConfigItem<"magic-comment.includeFiles">,
  /**
   * Enabled in languages
   * @key `magic-comment.supportLanguages`
   * @default `[]`
   * @type `array`
   */
  supportLanguages: {
    key: "magic-comment.supportLanguages",
    default: [],
  } as ConfigItem<"magic-comment.supportLanguages">,
  /**
   * User defined magic comments
   * @key `magic-comment.userComments`
   * @default `[]`
   * @type `array`
   */
  userComments: {
    key: "magic-comment.userComments",
    default: [],
  } as ConfigItem<"magic-comment.userComments">,
}

export interface ScopedConfigKeyTypeMap {
  "annotation": { 'after': { 'contentText': string; 'margin': string }; 'color': string },
  "disabledCategories": string[],
  "disabledNames": string[],
  "enable": boolean,
  "excludeFiles": string[],
  "includeFiles": string[],
  "supportLanguages": string[],
  "userComments": { 'category': string; 'description': string; 'examples': string[]; 'name': string; 'patterns': unknown; 'url': string }[],
}

export const scopedConfigs = {
  scope: "magic-comment",
  defaults: {
    "annotation": { "after": { "contentText": "🚀", "margin": "0 0 0 0.5em" }, "color": "rgb(255, 189, 42)" },
    "disabledCategories": [],
    "disabledNames": [],
    "enable": true,
    "excludeFiles": [],
    "includeFiles": [],
    "supportLanguages": [],
    "userComments": [],
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "magic-comment": {
    "annotation": { 'after': { 'contentText': string; 'margin': string }; 'color': string },
    "disabledCategories": string[],
    "disabledNames": string[],
    "enable": boolean,
    "excludeFiles": string[],
    "includeFiles": string[],
    "supportLanguages": string[],
    "userComments": { 'category': string; 'description': string; 'examples': string[]; 'name': string; 'patterns': unknown; 'url': string }[],
  },
}

export interface NestedScopedConfigs {
  "annotation": { 'after': { 'contentText': string; 'margin': string }; 'color': string },
  "disabledCategories": string[],
  "disabledNames": string[],
  "enable": boolean,
  "excludeFiles": string[],
  "includeFiles": string[],
  "supportLanguages": string[],
  "userComments": { 'category': string; 'description': string; 'examples': string[]; 'name': string; 'patterns': unknown; 'url': string }[],
}

