// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "magic-comment"
export const version = "0.0.0"
export const displayName = "Magic Comment"
export const description = "Add annotations to magic comments"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "magic-comment.getLanguageConfig"

/**
 * Commands map registed by `ntnyq.magic-comment`
 */
export const commands = {
  /**
   * getLanguageConfig
   * @value `magic-comment.getLanguageConfig`
   */
  getLanguageConfig: "magic-comment.getLanguageConfig",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = 
  | "magic-comment.enable"
  | "magic-comment.excludeFiles"
  | "magic-comment.includeFiles"
  | "magic-comment.supportLanguages"
  | "magic-comment.userComments"
  | "magic-comments.disabledCategories"
  | "magic-comments.disabledComments"

export interface ConfigKeyTypeMap {
  "magic-comment.enable": boolean,
  "magic-comment.excludeFiles": string[],
  "magic-comment.includeFiles": string[],
  "magic-comment.supportLanguages": string[],
  "magic-comment.userComments": string[],
  "magic-comments.disabledCategories": string[],
  "magic-comments.disabledComments": string[],
}

export interface ConfigShorthandMap {
  enable: "magic-comment.enable",
  excludeFiles: "magic-comment.excludeFiles",
  includeFiles: "magic-comment.includeFiles",
  supportLanguages: "magic-comment.supportLanguages",
  userComments: "magic-comment.userComments",
  magicCommentsDisabledCategories: "magic-comments.disabledCategories",
  magicCommentsDisabledComments: "magic-comments.disabledComments",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  excludeFiles: string[],
  includeFiles: string[],
  supportLanguages: string[],
  userComments: string[],
  magicCommentsDisabledCategories: string[],
  magicCommentsDisabledComments: string[],
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.magic-comment`
 */
export const configs = {
  /**
   * Enable extension
   * @key `magic-comment.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "magic-comment.enable",
    default: true,
  } as ConfigItem<"magic-comment.enable">,
  /**
   * Exclude files
   * @key `magic-comment.excludeFiles`
   * @default `[]`
   * @type `array`
   */
  excludeFiles: {
    key: "magic-comment.excludeFiles",
    default: [],
  } as ConfigItem<"magic-comment.excludeFiles">,
  /**
   * Include files
   * @key `magic-comment.includeFiles`
   * @default `[]`
   * @type `array`
   */
  includeFiles: {
    key: "magic-comment.includeFiles",
    default: [],
  } as ConfigItem<"magic-comment.includeFiles">,
  /**
   * Enabled in languages
   * @key `magic-comment.supportLanguages`
   * @default `[]`
   * @type `array`
   */
  supportLanguages: {
    key: "magic-comment.supportLanguages",
    default: [],
  } as ConfigItem<"magic-comment.supportLanguages">,
  /**
   * User defined magic comments
   * @key `magic-comment.userComments`
   * @default `[]`
   * @type `array`
   */
  userComments: {
    key: "magic-comment.userComments",
    default: [],
  } as ConfigItem<"magic-comment.userComments">,
  /**
   * Disabled by category name
   * @key `magic-comments.disabledCategories`
   * @default `[]`
   * @type `array`
   */
  magicCommentsDisabledCategories: {
    key: "magic-comments.disabledCategories",
    default: [],
  } as ConfigItem<"magic-comments.disabledCategories">,
  /**
   * Disabled by comments name
   * @key `magic-comments.disabledComments`
   * @default `[]`
   * @type `array`
   */
  magicCommentsDisabledComments: {
    key: "magic-comments.disabledComments",
    default: [],
  } as ConfigItem<"magic-comments.disabledComments">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "excludeFiles": string[],
  "includeFiles": string[],
  "supportLanguages": string[],
  "userComments": string[],
}

export const scopedConfigs = {
  scope: "magic-comment",
  defaults: {
    "enable": true,
    "excludeFiles": [],
    "includeFiles": [],
    "supportLanguages": [],
    "userComments": [],
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "magic-comment": {
    "enable": boolean,
    "excludeFiles": string[],
    "includeFiles": string[],
    "supportLanguages": string[],
    "userComments": string[],
  },
  "magic-comments": {
    "disabledCategories": string[],
    "disabledComments": string[],
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "excludeFiles": string[],
  "includeFiles": string[],
  "supportLanguages": string[],
  "userComments": string[],
}

